Script. Js
inIcALIZAÇÃO === function inicializarDados() {     const salvos = localStorage.getItem('paoDuroCarteira');     if (salvos) carteira = JSON.parse(salvos);     const favSalvos = localStorage.getItem('paoDuroFavoritos');     if (favSalvos) favoritos = JSON.parse(favSalvos);     atualizarTabelaCarteira();     atualizarFiltroAnos();     atualizarTabelaFavoritos(); }
function salvarCarteira() {     localStorage.setItem('paoDuroCarteira', JSON.stringify(carteira));     atualizarFiltroAnos(); }
function salvarFavoritos() {     localStorage.setItem('paoDuroFavoritos', JSON.stringify(favoritos)); }
// ========== NAVEGAÇÃO DE ABAS ========== function trocarAba(indice) {     abaAtiva = indice;     botoesAbas.forEach((botao, i) => botao.classList.toggle('ativo', i === indice));     conteudoAbas.forEach((conteudo, i) => conteudo.classList.toggle('visivel', i === indice));     if (indice === 1) {         atualizarTabelaCarteira();         esconderMovimentacoes();         esconderAnexo();     }     if (indice === 2) atualizarTabelaFavoritos(); }
// ========== CÁLCULOS ========== function calcularGraham(vpa, lpa) {     if (!vpa || !lpa || vpa <= 0 || lpa <= 0) return null;     return Math.sqrt(22.5 * vpa * lpa); }
function calcularBazin(lpa, dividendYield, precoAtual) {     if (!lpa || lpa <= 0 || !dividendYield || dividendYield <= 0 || !precoAtual) return null;     const taxa = 0.06;     const dy = dividendYield / 100;     const dividendoAnual = precoAtual * dy;     return dividendoAnual / taxa; }
function calcularPeterLynch(precoAtual, crescimentoAnual, dividendYield) {     if (!crescimentoAnual || crescimentoAnual <= 0 || !precoAtual) return null;     const taxaCresc = crescimentoAnual / 100;     const dy = dividendYield ? dividendYield / 100 : 0;     return precoAtual * (taxaCresc + dy); }
function formatarMoeda(valor) {     if (valor === null || valor === undefined || isNaN(valor)) return '---';     return 'R$ ' + valor.toFixed(2).replace('.', ','); }
function formatarPercentual(valor) {     if (valor === null || valor === undefined || isNaN(valor)) return '---';     const sinal = valor >= 0 ? '+' : '';     return `${sinal}${valor.toFixed(2).replace('.', ',')}%`; }
       // === p === p ===BUSCA DE AÇÃO — API REAL ========== async function buscarAcao() {     const codigo = document.getElementById('campoPesquisa').value.trim().toUpperCase();     if (!codigo) { alert('Digite o código da ação! Ex: PETR4'); return; }     const corpo = document.getElementById('corpoTabela');     corpo.innerHTML = '<tr><td colspan="6" style="text-align:center;padding:20px;color:#2ecc71">🔄 Buscando dados reais... Aguarde...</td></tr>';          try {         const url = `https://brapi.dev/api/quote/${codigo}?modules=defaultKeyStatistics`;         const resposta = await fetch(url);         const dados = await resposta.json();                  if (!dados.results || dados.results.length === 0) {             corpo.innerHTML = '<tr><td colspan="6" style="text-align:center;padding:20px;color:red">❌ Ativo não encontrado! Tente: PETR4, VALE3, ITUB4 ou MGLU3</td></tr>';             return;         }
E